trigger:
  - main

pool:
  vmImage: ubuntu-latest

variables:
  buildDirectory: build

steps:
  - task: CMake@1
    displayName: Configure (CMake)
    inputs:
      workingDirectory: $(buildDirectory)
      cmakeArgs: >-
        ..
        -DCMAKE_BUILD_TYPE=Release

  - task: CMake@1
    displayName: Build
    inputs:
      workingDirectory: $(buildDirectory)
      cmakeArgs: --build . --config Release

  - script: $(buildDirectory)/calculator
    displayName: Run calculator
