# This section defines the trigger(s) for the pipeline.
# 'main' specifies that the pipeline will run whenever changes are pushed to the 'main' branch.
trigger:
- main  # automatically triggers this pipeline when changes are made to the 'main' branch.

# This defines the pool where the pipeline will run.
pool:
  name: Controller-Plattform-Docker-Agent-Pool

# Steps contain the individual tasks or actions that the pipeline will execute.
steps:
- script: |
    sudo apt-get update
    sudo apt-get install -y cmake g++
  displayName: 'Install CMake and GCC'

- script: |
    cmake -S . -B build -DCMAKE_BUILD_TYPE=Release
  displayName: 'Configure CMake'

- script: |
    cmake --build build --config Release
  displayName: 'Build project'

- script: |
    cd build && ctest --output-on-failure
  displayName: 'Run tests'
